name: Run Vue Bypass

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Chromium Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 libatk1.0-0 libcups2 libxcomposite1 \
            libxdamage1 libxrandr2 libgbm1 libasound2t64 \
            libpangocairo-1.0-0 libgtk-3-0

      - name: Install NPM deps
        run: npm install

      - name: Install Browser
        run: npm run install-browser

      - name: Run Scraper
        run: npm start
